name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs
  cancel-in-progress: true

env:
  PAGES_ARTIFACT_NAME: github-pages-${{ github.run_attempt }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Zensical
        run: pip install zensical==0.0.31

      - name: Build docs
        run: zensical build --clean

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ env.PAGES_ARTIFACT_NAME }}
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.PAGES_ARTIFACT_NAME }}
